sudo: false

language: go

before_install:
 # Required for format check.
 - go get golang.org/x/tools/cmd/goimports
 # Required for coverage.
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - ${TRAVIS_BUILD_DIR}/.travis/check-formatting.sh
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash ./.travis/test-coverage.sh; fi